### ISSUE TITLE
Paging links are incorrect

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/gofhir#18]
If you access Bundle search results (in `Bundle.link`), the paging links are incorrectly encoded.

For example,

https://syntheticmass.mitre.org/fhir/Patient?_offset=100\u0026_count=100

should be

https://syntheticmass.mitre.org/fhir/Patient?_offset=100&_count=100

**Comment by cjduffett** [comment]
They're essentially the same - one is just URL escaped and one is not. For now, could you wrap your use of them in a call to url.Unescape(link) until we can update the server? Moving this issue to the intervention-engine/fhir repository.

**Comment by jawalonoski** [comment]
I know. I don't need the work around. It was a bug reported to me and I'm simply reporting it. I'd like it fixed before the AMIA Datathon.
